# certificate-authority-data, client-certificate-data, client-key-data can be taken from kubectl command below.

apiVersion: v1
clusters:
- cluster:
    # kubectl config view --raw -o jsonpath='{.clusters[0].cluster.certificate-authority-data}'
    certificate-authority-data: ...
    server: https://127.0.0.1:6443
  name: default
contexts:
- context:
    cluster: default
    user: default
  name: default
current-context: default
kind: Config
preferences: {}
users:
- name: default
  user:
    # kubectl config view --raw -o jsonpath='{.users[0].user.client-certificate-data}'
    client-certificate-data: ...
    # kubectl config view --raw -o jsonpath='{.users[0].user.client-key-data}'
    client-key-data: ...
